version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: property-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis:latest
    container_name: prop-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
